
const data = [
  {
    topic: 'Art',
    teachers: [
      {
        id: 0,
        username: 'VincentVanUgh',
        viewers: 123,
        followers: 124,
        description: 'Come hear to learn the art of one ear',
        image: 'https://s3.amazonaws.com/uifaces/faces/twitter/doooon/128.jpg',
      },
      {
        id: 1,
        username: 'DatGuyLeonardo',
        viewers: 234,
        followers: 210,
        description: 'Erudite scholar looking to educate mad lads',
        image:' https://s3.amazonaws.com/uifaces/faces/twitter/gonzalorobaina/128.jpg',
      },
      {
        id: 2,
        username: 'DrPepperLive',
        viewers: 530,
        followers: 409,
        description: 'Get better with Dr Pepper',
        image: 'https://s3.amazonaws.com/uifaces/faces/twitter/zackeeler/128.jpg',
      },
      {
        id: 3,
        username: 'SmartArt',
        viewers: 1293,
        followers: 1243,
        description: 'Work Smart, Not Hard',
        image: 'https://s3.amazonaws.com/uifaces/faces/twitter/mkginfo/128.jpg',
      },
    ],
  },
  {
    topic: 'Cooking',
    teachers: [
      {
        id: 4,
        username: 'MasterChef',
        viewers: 1233,
        followers: 1124,
        description: 'Halo is the way yo',
        image: 'https://s3.amazonaws.com/uifaces/faces/twitter/dudestein/128.jpg',
        
      },
      {
        id: 5,
        username: 'RamRamsey',
        viewers: 2340,
        followers: 2910,
        description: 'GET OUT OF MY CLASSROOM!',
        image: 'https://s3.amazonaws.com/uifaces/faces/twitter/ariffsetiawan/128.jpg',
      },
      {
        id: 6,
        username: 'MommaDeen',
        viewers: 510,
        followers: 439,
        description: 'Butter Butter Butter',
        image: 'https://s3.amazonaws.com/uifaces/faces/twitter/thomasschrijer/128.jpg',
      },
      {
        id: 7,
        username: 'SousVide',
        viewers: 793,
        followers: 843,
        description: 'Set it and forget it',
        image: 'https://s3.amazonaws.com/uifaces/faces/twitter/marclgonzales/128.jpg',
      },
    ],
  },
  {
    topic: 'Foreign Language',
    teachers: [
      {
        id: 8,
        username: 'BangALang',
        viewers: 1323,
        followers: 1424,
        description: 'La cucaracha la cucaracha',
        image: 'https://s3.amazonaws.com/uifaces/faces/twitter/Shriiiiimp/128.jpg',
      },
      {
        id: 9,
        username: 'BirdsTheWord',
        viewers: 694,
        followers: 490,
        description: 'Learn words with Birds',
        image: 'https://s3.amazonaws.com/uifaces/faces/twitter/fronx/128.jpg',
      },
      {
        id: 10,
        username: 'HolaComoEsta',
        viewers: 400,
        followers: 479,
        description: 'Hello, how are you?',
        image: 'https://s3.amazonaws.com/uifaces/faces/twitter/maximsorokin/128.jpg',
      },
      {
        id: 11,
        username: 'Aubergine',
        viewers: 193,
        followers: 243,
        description: 'Eggplant',
        image: 'https://s3.amazonaws.com/uifaces/faces/twitter/mdsisto/128.jpg',
      },
    ],
  },
  {
    topic: 'Math',
    teachers: [
      {
        id: 12,
        username: 'Fibonacci',
        viewers: 2123,
        followers: 2224,
        description: 'Hmph',
        image: 'https://s3.amazonaws.com/uifaces/faces/twitter/wake_gs/128.jpg',
      },
      {
        id: 13,
        username: 'MathMagician',
        viewers:1834,
        followers: 1910,
        description: 'Numbers with magic',
        image: 'https://s3.amazonaws.com/uifaces/faces/twitter/sreejithexp/128.jpg',
      },
      {
        id: 14,
        username: 'why789',
        viewers: 320,
        followers: 209,
        description: 'Come here to find out why seven ate nine!',
        image: 'https://s3.amazonaws.com/uifaces/faces/twitter/jjshaw14/128.jpg',
      },
      {
        id: 15,
        username: 'OnePlueOne',
        viewers: 593,
        followers: 743,
        description: 'Basic Math for everyone to learn',
        image: 'https://s3.amazonaws.com/uifaces/faces/twitter/mgonto/128.jpg',
      },
    ],
  },
  {
    topic: 'Yoga',
    teachers: [
      {
        id: 16,
        username: 'larrychangg',
        viewers: 333,
        followers: 214,
        description: 'The best yoga teacher ever and good-looking too, Huzzah!',
        image: 'https://s3.amazonaws.com/uifaces/faces/twitter/justme_timothyg/128.jpg',
      },
      {
        id: 17,
        username: 'Funyuns',
        viewers: 434,
        followers: 267,
        description: 'I love to eat, but I also love YOGA. Newcomers always welcome',
        image: 'https://s3.amazonaws.com/uifaces/faces/twitter/katiemdaly/128.jpg',
      },
      {
        id: 18,
        username: 'DangItsKang',
        viewers: 398,
        followers: 320,
        description: 'Unbelievable Yoga with the one and only DangItsKang. Come and try you will love it.',
        image: 'https://s3.amazonaws.com/uifaces/faces/twitter/davidbaldie/128.jpg',
      },
      {
        id: 19,
        username: 'FitToBeUnfit',
        viewers: 255,
        followers: 69,
        description: 'The best worst experience you can ever have with Yoga. Find out what I mean Hehe',
        image: 'https://s3.amazonaws.com/uifaces/faces/twitter/instalox/128.jpg',
      },
    ],
  },
];

module.exports = {
  data,
};
